# Generates CartridgePrograms.inc from the .spn sources in app/programs.
# Invoked as: cmake -DPROGRAM_DIR=... -DOUT=... -P EmbedPrograms.cmake
# The table order defines the cartridge/program indices used engine-wide.

set(entries
    "cathedral|1-shimmer|CATHEDRAL|SHIMMER"
    "cathedral|2-octdelay|CATHEDRAL|OCT-UP DELAY"
    "cathedral|3-space|CATHEDRAL|SPACE REVERB"
    "time|1-delayverb|TIME|DELAY REVERB"
    "time|2-delaychorus|TIME|DELAY CHORUS"
    "time|3-delayvibrato|TIME|DELAY VIBRATO"
    "vibrotrem|1-tremolo|VIBROTREM|TREMOLO"
    "vibrotrem|2-vibrato|VIBROTREM|VIBRATO"
    "vibrotrem|3-chorus|VIBROTREM|CHORUS"
    "ochre|1-reverse-long|OCHRE|REVERSE ONE-SHOT LONG"
    "ochre|2-reverse-short|OCHRE|REVERSE ONE-SHOT SHORT"
    "ochre|3-reverse-loop|OCHRE|REVERSE LOOP"
)

set(body "// Auto-generated by EmbedPrograms.cmake from app/programs — do not edit.\n")
string(APPEND body "static constexpr CartridgeLibrary::Entry kEntries[] = {\n")

foreach(entry IN LISTS entries)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 dir)
    list(GET parts 1 file)
    list(GET parts 2 cart)
    list(GET parts 3 name)
    file(READ "${PROGRAM_DIR}/${dir}/${file}.spn" source)
    string(APPEND body "    { \"${cart}\", \"${name}\",\n      R\"S42SPN(${source})S42SPN\" },\n")
endforeach()

string(APPEND body "};\n")
file(WRITE "${OUT}" "${body}")
